# Generated by Django 5.1 on 2024-11-11 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_code', models.CharField(max_length=55)),
                ('building_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_buildings',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_colleges',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=55)),
                ('course_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_courses',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_sections',
            },
        ),
        migrations.CreateModel(
            name='YearSem',
            fields=[
                ('yearSem_id', models.AutoField(primary_key=True, serialize=False)),
                ('yearLevel', models.CharField(max_length=55)),
                ('semester', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'tbl_yearSem',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, default=3, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CourseYearSem',
            fields=[
                ('courseYearSem_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.course')),
                ('yearSem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.yearsem')),
            ],
            options={
                'db_table': 'tbl_courseYearSem',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.college')),
            ],
            options={
                'db_table': 'tbl_programs',
            },
        ),
        migrations.CreateModel(
            name='CourseProgram',
            fields=[
                ('courseProgram_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.program')),
            ],
            options={
                'db_table': 'tbl_courseProgram',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('roomType', models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], default='Single', max_length=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.building')),
            ],
            options={
                'db_table': 'tbl_rooms',
            },
        ),
        migrations.CreateModel(
            name='ProgramSection',
            fields=[
                ('programSection_id', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.program')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.section')),
            ],
            options={
                'db_table': 'tbl_programSection',
            },
        ),
        migrations.CreateModel(
            name='SectionYearSem',
            fields=[
                ('sectionYearSem_id', models.AutoField(primary_key=True, serialize=False)),
                ('courseYearSem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.courseyearsem')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.section')),
                ('yearSem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.yearsem')),
            ],
            options={
                'db_table': 'tbl_sectionYearSem',
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('examSchedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('examDescription', models.CharField(max_length=55)),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('courseProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.courseprogram')),
                ('courseYearSem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.courseyearsem')),
                ('proctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.room')),
                ('sectionYearSem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.sectionyearsem')),
            ],
            options={
                'db_table': 'tbl_examSchedule',
            },
        ),
    ]
