# Generated by Django 5.1 on 2024-11-11 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_building_college_course_section_yearsem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionyearsem',
            name='courseYearSem',
        ),
        migrations.AddField(
            model_name='courseyearsem',
            name='courseProgram',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.courseprogram'),
            preserve_default=False,
        ),
    ]
